### ISSUE TITLE
API updated

### ISSUE THREAD

**Issue by berylrubacky** [msruback/MoNet2#9]
The api updated yesterday, possibly when the Nintendo Direct went up. Since it seems data on the api is not currently being updated, I need to intercept the api calls the official app uses using mitmproxy.

**Comment by berylrubacky** [comment]
Issue seems to be the mystery parameter F. It seems to be calculated somehow.

**Comment by berylrubacky** [comment]
Unpacking the official app to get access to how f is calculated

**Comment by msruback** [comment]
There doesn't appear to be a fix, killing this app

**Comment by berylrubacky** [comment]
For now, until f can be figured out, I am using mitmproxy to capture the cookie

**Comment by berylrubacky** [comment]
Until f is figured out, (I suspect it is a hash of the id token), Users should be able to provide their iksm token manually, having been obtained from mitmproxy

**Comment by berylrubacky** [comment]
It appears that f is not going to figured out anytime soon. Furthermore, if it is, it is only a matter of time before Nintendo secures their API further. It is best to accept that users will have to be able to provide their own cookie.

**Comment by berylrubacky** [comment]
Users can now provide their cookie in the settings, however new users should be prompt upon loading the app.

**Comment by berylrubacky** [comment]
API changes are now dealt with
